// Species list, from "Trees & Shrubs to be metal tagged w/ QR code for care instruction".
// `care` is the page each species' QR tag links to.
const species = {
    "rainier-cherry":       { name: "Rainier Cherry",                  care: "https://bettyscommunitygarden.org/tree-shrub-care/rainier-cherry-draft/" },
    "cherry":               { name: "Cherry",                          care: "https://bettyscommunitygarden.org/tree-shrub-care/cherry/" },
    "yoshino-cherry":       { name: "Yoshino Cherry",                  care: "https://bettyscommunitygarden.org/tree-shrub-care/yoshino-cherry/" },
    "asian-pear":           { name: "Asian Pear",                      care: "https://bettyscommunitygarden.org/tree-shrub-care/asian-pear/" },
    "apricot":              { name: "Apricot",                         care: "https://bettyscommunitygarden.org/tree-shrub-care/apricot/" },
    "peach":                { name: "Peach",                           care: "https://bettyscommunitygarden.org/tree-shrub-care/peach/" },
    "green-apple":          { name: "Green Apple",                     care: "https://bettyscommunitygarden.org/tree-shrub-care/green-apple/" },
    "grapes":               { name: "Grapes (Thompson Seedless)",      care: "https://bettyscommunitygarden.org/tree-shrub-care/grapes-thompson-seedless/" },
    "blackberries":         { name: "Blackberries",                    care: "https://bettyscommunitygarden.org/tree-shrub-care/blackberries/" },
    "raspberries":          { name: "Raspberries",                     care: "https://bettyscommunitygarden.org/tree-shrub-care/raspberries/" },
    "hydrangea":            { name: "Hydrangea (Endless Summer)",      care: "https://bettyscommunitygarden.org/tree-shrub-care/endless-summer-hydrangea/" },
    "tatarian-dogwood":     { name: "Tatarian Dogwood",                care: "https://bettyscommunitygarden.org/tree-shrub-care/tatarian-dogwood/" },
    "kousa-dogwood":        { name: "Kousa Dogwood",                   care: "https://bettyscommunitygarden.org/tree-shrub-care/kousa-dogwood/" },
    "hybrid-tea-rose":      { name: "Hybrid Tea Rose",                 care: "https://bettyscommunitygarden.org/tree-shrub-care/hybrid-tea-rose/" },
    "shrub-climbing-rose":  { name: "Shrub Climbing Rose",             care: "https://bettyscommunitygarden.org/tree-shrub-care/shrub-climbing-rose/" },
    "shrub-rose":           { name: "Shrub Rose",                      care: "https://bettyscommunitygarden.org/tree-shrub-care/shrub-rose/" },
    "russian-pomegranate":  { name: "Russian Pomegranate",             care: "https://bettyscommunitygarden.org/tree-shrub-care/russian-pomegranate/" },
    "mulberry":             { name: "Mulberry",                        care: "https://bettyscommunitygarden.org/tree-shrub-care/mulberry/" },
    "hachiku-bamboo":       { name: "Hachiku Bamboo (Henon Bamboo)",   care: "https://bettyscommunitygarden.org/tree-shrub-care/henon-hachiku-bamboo/" },
    "arrow-bamboo":         { name: "Arrow Bamboo",                    care: "https://bettyscommunitygarden.org/tree-shrub-care/arrow-bamboo/" },
    "elderberry":           { name: "Elderberry",                      care: "https://bettyscommunitygarden.org/tree-shrub-care/elderberry/" },
    "fig":                  { name: "Fig",                             care: "https://bettyscommunitygarden.org/tree-shrub-care/fig/" },
    "common-lilac":         { name: "Common Lilac",                    care: "https://bettyscommunitygarden.org/tree-shrub-care/common-lilac/" },
    "rose-of-sharon":       { name: "Rose of Sharon",                  care: "https://bettyscommunitygarden.org/tree-shrub-care/rose-of-sharon/" },
    "japanese-spindle":     { name: "Japanese Spindle (Masaki)",       care: "https://bettyscommunitygarden.org/tree-shrub-care/japanee-spindle-masaki/" },
    "common-box":           { name: "Common Box",                      care: "https://bettyscommunitygarden.org/tree-shrub-care/common-box/" },
    "weeping-holly":        { name: "Weeping Holly",                   care: "https://bettyscommunitygarden.org/tree-shrub-care/weeping-holly/" },
    "blue-holly":           { name: "Blue Holly",                      care: "https://bettyscommunitygarden.org/tree-shrub-care/blue-holly/" },
    "eastern-red-cedar":    { name: "Eastern Red Cedar",               care: "https://bettyscommunitygarden.org/tree-shrub-care/eastren-red-cedar/" },
    "arborvitae":           { name: "Arborvitae (Eastern White Cedar)", care: "https://bettyscommunitygarden.org/tree-shrub-care/arborvitae-eastern-white-cedar/" },
    "yew":                  { name: "Yew",                             care: "https://bettyscommunitygarden.org/tree-shrub-care/yew/" },
    "inkberry":             { name: "Inkberry",                        care: "https://bettyscommunitygarden.org/tree-shrub-care/inkberry/" },
    "common-hackberry":     { name: "Common Hackberry",                care: "https://bettyscommunitygarden.org/tree-shrub-care/common-hackberry/" },
    "spruce":               { name: "Spruce",                          care: "https://bettyscommunitygarden.org/tree-shrub-care/spruce/" },
    "sawara-cypress":       { name: "Sawara Cypress",                  care: "https://bettyscommunitygarden.org/tree-shrub-care/sawara-cypress/" },
    "eastern-hemlock":      { name: "Eastern Hemlock",                 care: "https://bettyscommunitygarden.org/tree-shrub-care/eastern-hemlock/" },
    "japanese-pagoda-tree": { name: "Japanese Pagoda Tree",            care: "https://bettyscommunitygarden.org/tree-shrub-care/japanese-pagpda-tree/" }
};

// Individual plants on the map, keyed to the shapes in assets/TO LEAFLET.svg.
//   name:    where it is in the garden (shown in the popup)
//   species: optional key from the list above, e.g. species: "mulberry"
//            (its name becomes the map label and the popup links to its care page)
//   shape:   the shape's position in the SVG file — open map.html?debug to see the numbers
const gardenFeatures = [
    { name: "Mulberry tree by cats", shape: 1 },
    { name: "Back of shed mulberry tree", shape: 0 },
    { name: "Bottom left gazebo bush", shape: 25 },
    { name: "Oak cat tree", shape: 5 },
    { name: "Bamboo cats", shape: 6 },
    { name: "Pomegranate tree", shape: 8 },
    { name: "Primary cherry tree", shape: 7 },
    { name: "Fig tree", shape: 10 },
    { name: "Oak behind compost 1", shape: 11 },
    { name: "Oak behind compost 2", shape: 12 },
    { name: "Apricot", shape: 15 },
    { name: "Back bamboo", shape: 13 },
    { name: "Back left oak", shape: 17 },
    { name: "Hemlock tree", shape: 16 },
    { name: "Large pear", shape: 17 },
    { name: "Memorial plot", id: "memorial-plot" },
    { name: "Reiko cherry tree", shape: 19 },
    { name: "Cedar right 4", shape: 20 },
    { name: "Cedar right 3", shape: 21 },
    { name: "Cedar right 2", shape: 22 },
    { name: "Cedar right 1", shape: 23 },
    { name: "Apple tree", shape: 3 },
    { name: "Bottom right gazebo bush", shape: 24 },
    { name: "Tree left of Reiko cherry", shape: 26 },
    { name: "Mulberry gate", shape: 27 },
    { name: "Boxwood", shape: 28 },
    { name: "Gate rose bush", shape: 29 },
    { name: "Cedar left 4", shape: 30 },
    { name: "Cedar left 3", shape: 31 },
    { name: "Cedar left 2", shape: 32 },
    { name: "Cedar left 1", shape: 33 },
    { name: "Rosebush compost", shape: 34 },
    { name: "Yew bottom left", shape: 35 },
    { name: "Yew bottom top left", shape: 36 },
    { name: "Sour cherry tree", shape: 17 },
    { name: "Japanese pear", shape: 16 },
    { name: "Yew tree", shape: 9 }
];
